gfx/env/spaceup.tga
gfx/env/spacedn.tga
gfx/env/spacelf.tga
gfx/env/spacert.tga
gfx/env/spaceft.tga
gfx/env/spacebk.tga
models/smann.mdl
models/contest_models/($z)ejika2.mdl
models/lethal/box_h2.mdl
models/lethal/box_h3.mdl
models/lethal/gift4.mdl
models/lethal/gift3.mdl
models/lethal/ruddy.mdl
models/lethal/santac.mdl
sound/lethal/xmas/wwishu.wav
sound/lethal/xmas/deckhall.wav
sound/lethal/xmas/wwland.wav
sound/nm_goodbadugly.wav
sprites/lethal/lcs1.spr
sprites/lethal/lcs3.spr

